print ("Schoopl Managament System ")
name = input("Enter Student Name:")
age= int(input("Enter Student Age:"))
course=input("Entyer the Course:")
email=input("Enter the Email:")
phone=int(input("Enter the Phone Number:"))
graduation_year=int(input("Enter the Graduation Year:"))
print (f"Name:{name}\n Age:{age}\nCourse: {course}\nEmail: {email}\nPhone: {phone}\nGraduation Year: {graduation_year}")
